kind: pipeline
name: default
#Test
steps:
- name: build
  image: docker
  commands:
  - docker build .
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
